### PR TITLE
efloehr initial refactor to generate images to disk

### PR DESCRIPTION
**Pull request by efloehr**
This refactor starts with Jim Prior's refactor. Thank you Jim!

Much of Jim's comments shows iterations over some "m" search space, like 1/width, 2/width, 3/width, etc.

The goal of this refactor was to generate a bunch of images to disk, rather than display interactively.
This allows searching the "m" space quickly and allows for making movies.

### CODE REVIEW

**Comment by james-prior** [comment]
I have not run the code yet, but love the idea of making movies
of interating over small (or large) changes in parameters.

Like you are doing now, I have continued playing with code after
a meeting for a challenge.
I think it's good to put such code in an "after-meeting" branch,
and have pushed your code as such a branch.
I think it's good to leave the master branch for stuff that was submitted before the meeting.

**Comment by james-prior** [comment]
By the way, the way I pushed your stuff to https://github.com/cohpy/challenge-201608-refactor/,
was all local on my machine without doing anything on github.com.
The only stuff I did on github.com was to add comments and
close the pull request because github does not recognize that I pushed your stuff to cohpy,
since I did so in a branch other that was you requested the pull for.

The sequence was something like

git remote add efloehr https://github.com/efloehr/challenge-201608-refactor.git
git fetch efloehr
git checkout efloehr/efloehr
git checkout -b after-meeting
git push cohpy after-meeting

By doing all that from a local machine and avoiding clicking on the merge button
on github's web pages, unnecessary merge commits are avoided.

We should play with git and github together.
I have learned more about using git and github the last few months,
especially about using rebase and remote commands.

The following commits/branches all have exactly the same code,
but their histories are different. Explore and compare their histories.
https://github.com/james-prior/challenge-201608-refactor/commit/3e3a8f2e3104fde9b37e5347d9e5444601c8158d
https://github.com/james-prior/challenge-201608-refactor/tree/straight-line
https://github.com/james-prior/challenge-201608-refactor/tree/straight-line-cleaned-up
https://github.com/james-prior/challenge-201608-refactor/tree/straight-line-cleaned-up-reordered
https://github.com/james-prior/challenge-201608-refactor/tree/straight-line-cleaned-up-reordered-2

**Comment by james-prior** [comment]
Folks love pretty pictures.

You should show your movies at the next meeting.

**Comment by efloehr** [comment]
Thanks, and your command line merging the pull request is great, it will be nice to sit down with you and share what you've learned.

I disagree about the post-meeting branch. I think master should reflect the most current code, unless post-meeting becomes the default branch instead of master. By default, master is the branch that gets shown when you go to the repo on github, and the selected branch when you clone or fork. As such, I think master should reflect the most current codebase.

My preferred solution, since most people associate master with the most current codebase, is to create a "pre-meeting" tag at the commit that was most current at the time of the meeting.

**Comment by james-prior** [comment]
On Tue, 27 Sep 2016 09:52:23 -0700, Eric Floehr notifications@github.com wrote:

> Thanks, and your command line merging the pull request is great,
>  it will be nice to sit down with you and share what you've learned.
> 
> I disagree about the post-meeting branch.
> I think master should reflect the most current code,
> unless post-meeting becomes the default branch instead of master.
> By default, master is the branch that gets shown when you go
> to the repo on github,
> and the selected branch when you clone or fork.
> As such, I think master should reflect the most current codebase.
> 
> My preferred solution, since most people associate master
> with the most current codebase, is to create a "pre-meeting"
> tag at the commit that was most current at the time of the meeting.

You can accomplish the above with something like the 
following commands.

git remote add cohpy git@github.com:cohpy/challenge-201608-refactor.git
git fetch cohpy
git checkout 2f758f5
git tag 20160926-meeting
git push cohpy 20160926-meeting

git checkout master
git merge efloehr
git push cohpy master

That will give you a little experience working with github
more from the command line. If you resurrect the pull request,
before before you do the git push cohpy master, you will see 
it as open. After you do the git push cohpy master, 
github will consider that to sate the pull request,
and without the ugly superfluous merge commit.

By the way, github does not seem to care much about tags.
They like to call them "releases" and when you navigate
to them, they want one to download the code as a tarball
or zip file, but do not show the code like for branches.
If you click on the hash for the tag, you will get to browse
the code.

**Comment by james-prior** [comment]
Do you want to save the above stuff for when we are side-by-side?

**Comment by efloehr** [comment]
We can save for when we are side-by-side.

Too bad about tags. I still believe that the latest code should be what shows up by default on github or clone. It only makes sense that people coming to this see the latest code as most likely that's what they want. That makes the repo a living repo instead of a dead one, and how anyone working with code naturally works.

If we want to capture a snapshot of how the repo existed at some point in time, we can create a branch, called "pre-meeting" or something.

Thoughts?

**Pull request closed without merging**
